### ISSUE TITLE
Indentation is wrong for an enum with EnumBaseType

### ISSUE THREAD

**Issue by landaire** [Emacs-D-Mode-Maintainers/Emacs-D-Mode#56] opened 2015-12-28 01:27 UTC
For an enum with a base type:

```
  enum : char {
    eof = cast(char)-1,
      openParen = '(',
      closeParen = ')',
      comment = ';'
  };
```

The indentation for all lines after the first (in this case eof) are indented one extra level. This does not occur with enums that don't have a base type specified.

**Comment by russel** [comment] 2016-03-28 17:50
I believe this is a duplicate of #19.

**Comment by CyberShadow** [comment] 2016-10-10 07:37
Closing per Russel's comment.

**Closed by CyberShadow** 2016-10-10 07:37 UTC
Labels: C:indentation, S:bug, S:duplicate
