### ISSUE TITLE
Pointer declaration colouring seems weird

### ISSUE THREAD

**Issue by russel** [Emacs-D-Mode-Maintainers/Emacs-D-Mode#82] opened 2017-06-03 18:05 UTC
It appears that:
```d
SomeType* v;
```
gets coloured differently to:
```d
SomeType * v;
```
and that the former is coloured correctly and the latter is not coloured at all.

**Comment by CyberShadow** [comment] 2017-06-05 11:36
Both look fine here:

![](https://dump.thecybershadow.net/08ab32f49dfcc15e7b91a2fff402e591/11%3A35%3A31-upload.png)

Is there anything else in the surrounding code that would affect fontification?

**Comment by CyberShadow** [comment] 2017-06-29 23:07
Managed to reproduce it (or a similar bug?) with:
```d
struct S
{
	this(Object o) {}
	this(Object* o) {}
}
```
`Object` in the second constructor definition isn't fontified as a type.

**Comment by mathias-lang-sociomantic** [comment] 2017-07-05 15:44
Works for me (although fontification happens at different stages).

**Comment by nandryshak** [comment] 2017-09-13 15:14
Changing the second constructor in CyberShadow's comment to:

    this(Object * o) {}

Break the fontification for me.

**Comment by CyberShadow** [comment] 2021-04-12 10:53
This and some other issues should have been auto-closed when #93 was merged, but for whatever reason, they were not. I'm manually closing them now.

**Closed by CyberShadow** 2021-04-12 10:53 UTC
Labels: C:fontification, T:bug
