### ISSUE TITLE
Incorrect escaping of string litterals

### ISSUE THREAD

**Issue by mathias-lang-sociomantic** [Emacs-D-Mode-Maintainers/Emacs-D-Mode#45] opened 2015-06-04 14:41 UTC
````
import std.stdio;
void main() { writeln(`This is an embedded \`); }
````
Emacs-D-Mode will highlight everything after the first backslash as string literal, but it shouldn't.

**Comment by russel** [comment] 2015-06-04 15:19
I believe this is a duplicate of #21 so I am closing this issue and keeping the older one.

**Closed by russel** 2015-06-04 15:19 UTC
