### ISSUE TITLE
2 Gentoo bug reports

### ISSUE THREAD

**Issue by toralf** [Emacs-D-Mode-Maintainers/Emacs-D-Mode#43] opened 2015-04-19 07:41 UTC
Pls might you have a look onto
https://bugs.gentoo.org/show_bug.cgi?id=536490
and
https://bugs.gentoo.org/show_bug.cgi?id=547026
?

**Comment by russel** [comment] 2015-06-04 15:28
The 2.0.6 release was 2013-06-22, there have been many changes since such that I am not sure it is viable to chase the issues down. We no longer issue releases, treating master/HEAD as the current rolling release, this then gets picked up my MELPA for the Emacs packaging system.  I suspect there will be little appetite to start making formal releases, so I think the best thing to do would be to package from master/HEAD using the commit date as the version number.

**Comment by CyberShadow** [comment] 2016-10-10 02:45
> https://bugs.gentoo.org/show_bug.cgi?id=547026

This seems to be a duplicate of #23.

> https://bugs.gentoo.org/show_bug.cgi?id=536490

Not sure about this one, since `cl-macroexpand-all` has never been used in d-mode, but seeing as it's from the `cl` package, it probably is related to the above.

Closing per Russel's comment.

**Closed by CyberShadow** 2016-10-10 02:45 UTC
